#include "../types/xsimd_sse_register.hpp"
#include "../types/xsimd_sse2_register.hpp"
#include "../types/xsimd_sse3_register.hpp"
#include "../types/xsimd_sse4_1_register.hpp"
#include "../types/xsimd_sse4_2_register.hpp"
#include "../types/xsimd_avx_register.hpp"
#include "../types/xsimd_avx2_register.hpp"
#include "../types/xsimd_avx512f_register.hpp"
