name: PowerPC cross-compilation build
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: '${{ matrix.target.platform }}, ${{ matrix.sys.compiler }} ${{ matrix.sys.version }}'
    strategy:
      matrix:
        target:
          - { platform: 'ppc64le', dir: 'powerpc64le-linux-gnu', full: 'OFF' }
          - { platform: 'ppc64',   dir: 'powerpc64-linux-gnu', full: 'OFF' }
        sys:
          - { compiler: 'gcc',   version: '12' }
          - { compiler: 'clang', version: '20', gcc_runtime: '12' }
    steps:
    - name: Checkout xsimd
      uses: actions/checkout@v6
    - name: Setup compiler
      id: setup-compiler
      uses: ./.github/actions/setup-cross-compiler-apt
      with:
        compiler: ${{ matrix.sys.compiler }}
        version: ${{ matrix.sys.version }}
        target: ${{ matrix.target.dir }}
        gcc-runtime: ${{ matrix.sys.gcc_runtime }}
        qemu: 'true'
    - name: Setup Ninja
      run: |
        sudo apt-get install ninja-build
    - name: Setup
      run: |
        cmake -B build/ \
              -DBUILD_TESTS=ON -DDOWNLOAD_DOCTEST=ON \
              -DBUILD_BENCHMARK=${{ matrix.target.full }} -DBUILD_EXAMPLES=${{ matrix.target.full }} \
              -DCMAKE_BUILD_TYPE=Release \
              -DTARGET_ARCH=vsx
    - name: Build
      run: cmake --build build/ --verbose -j1
    - name: Set CPU feature test expectations
      run: /bin/true
    - name: Testing xsimd
      run: |
        # Set CPU feature test expectations, 0 is explicit absence of the feature
        export XSIMD_TEST_CPU_ASSUME_SSE4_2="0"
        export XSIMD_TEST_CPU_ASSUME_NEON64="0"
        export XSIMD_TEST_CPU_ASSUME_RVV="0"
        export XSIMD_TEST_CPU_ASSUME_VXE="0"
        export XSIMD_TEST_CPU_ASSUME_VSX="1"

        ${{ steps.setup-compiler.outputs.qemu }} -cpu power10 ./build/test/test_xsimd
