name: PowerPC cross-compilation build
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: '${{ matrix.target.platform }}, ${{ matrix.sys.compiler }} ${{ matrix.sys.version }}'
    strategy:
      matrix:
        target:
          - { platform: 'ppc64le',     dir: 'powerpc64le-linux-gnu',   flags: '-maltivec -mvsx -mcpu=power10', full: 'OFF' }
          - { platform: 'ppc64',     dir: 'powerpc64-linux-gnu',   flags: '-maltivec -mvsx -mcpu=power10', full: 'OFF' }
        sys:
          - { compiler: 'gcc',   version: '12' }
          - { compiler: 'clang', version: '20', gcc_runtime: '12' }
    steps:
    - name: Setup GCC
      if: ${{ matrix.sys.compiler == 'gcc' }}
      run: |
        sudo apt-get update || exit 1
        sudo apt-get -y --no-install-suggests --no-install-recommends install g++-${{ matrix.sys.version }}-${{ matrix.target.dir }} g++-${{ matrix.sys.version }}-multilib cmake || exit 1
        sudo update-alternatives --remove-all ${{ matrix.target.dir }}-gcc || true
        sudo update-alternatives --remove-all ${{ matrix.target.dir }}-g++ || true
        sudo update-alternatives --install /usr/bin/${{ matrix.target.dir }}-gcc ${{ matrix.target.dir }}-gcc /usr/bin/${{ matrix.target.dir }}-gcc-${{ matrix.sys.version }} 20
        sudo update-alternatives --install /usr/bin/${{ matrix.target.dir }}-g++ ${{ matrix.target.dir }}-g++ /usr/bin/${{ matrix.target.dir }}-g++-${{ matrix.sys.version }} 20
    - name: Setup LLVM
      if: ${{ matrix.sys.compiler == 'clang' }}
      run: |
        sudo apt-get update || exit 1
        sudo apt-get -y --no-install-suggests --no-install-recommends install g++-${{ matrix.sys.gcc_runtime }}-${{ matrix.target.dir }} g++-${{ matrix.sys.gcc_runtime }}-multilib cmake || exit 1
        sudo apt-get -y --no-install-suggests --no-install-recommends install clang-${{ matrix.sys.version }} || exit 1
        sudo update-alternatives --remove-all /usr/bin/clang || true
        sudo update-alternatives --remove-all /usr/bin/clang++ || true
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${{ matrix.sys.version }} 20
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${{ matrix.sys.version }} 20
    - name: Setup QEMU
      run: |
        sudo apt-get --no-install-suggests --no-install-recommends install qemu-user
    - name: Setup Ninja
      run: |
        sudo apt-get install ninja-build
    - name: Checkout xsimd
      uses: actions/checkout@v6
    - name: Setup
      run: |
        cmake -B build/ \
              -DBUILD_TESTS=ON -DDOWNLOAD_DOCTEST=ON \
              -DBUILD_BENCHMARK=${{ matrix.target.full }} -DBUILD_EXAMPLES=${{ matrix.target.full }} \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_C_FLAGS="${{ matrix.target.flags }}" \
              -DCMAKE_CXX_FLAGS="${{ matrix.target.flags }}" \
              -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/.github/toolchains/${{ matrix.sys.compiler }}-${{ matrix.target.dir }}.cmake
    - name: Build
      run: cmake --build build/ --verbose -j1
    - name: Set CPU feature test expectations
      run: /bin/true
    - name: Testing xsimd
      run: |
        # Set CPU feature test expectations, 0 is explicit absence of the feature
        export XSIMD_TEST_CPU_ASSUME_SSE4_2="0"
        export XSIMD_TEST_CPU_ASSUME_NEON64="0"
        export XSIMD_TEST_CPU_ASSUME_RVV="0"
        export XSIMD_TEST_CPU_ASSUME_VXE="0"
        export XSIMD_TEST_CPU_ASSUME_VSX="1"

        qemu-${{ matrix.target.platform }} -cpu power10 -L /usr/${{ matrix.target.dir}}/ ./build/test/test_xsimd
