name: Arm-SVE cross-compilation build
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Arm SVE${{ matrix.vector_bits }}'
    strategy:
      matrix:
        vector_bits:
          - 128
          - 256
          - 512
    steps:
    - name: Checkout xsimd
      uses: actions/checkout@v6
    - name: Setup compiler
      id: setup-compiler
      uses: ./.github/actions/setup-cross-compiler-apt
      with:
        compiler: gcc
        version: '10'
        target: aarch64-linux-gnu
        qemu: 'true'
    - name: Setup Ninja
      run: |
        sudo apt-get install ninja-build
    - name: Setup
      run: |
        cmake -B _build \
              -GNinja \
              -DBUILD_TESTS=ON -DDOWNLOAD_DOCTEST=ON \
              -DCMAKE_BUILD_TYPE=Release \
              -DTARGET_ARCH=sve_${{ matrix.vector_bits }}
    - name: Build
      run: cmake --build _build
    - name: Set CPU feature test expectations
      run: |
        echo "XSIMD_TEST_CPU_ASSUME_SSE4_2=0" >> "$GITHUB_ENV"
        echo "XSIMD_TEST_CPU_ASSUME_RVV=0" >> "$GITHUB_ENV"
        echo "XSIMD_TEST_CPU_ASSUME_NEON64=1" >> "$GITHUB_ENV"
        echo "XSIMD_TEST_CPU_ASSUME_SVE=1"    >> "$GITHUB_ENV"
        echo "XSIMD_TEST_CPU_ASSUME_MANUFACTURER=unknown" >> "$GITHUB_ENV"
    - name: Testing xsimd
      run: ${{ steps.setup-compiler.outputs.qemu }} --cpu max,sve${{ matrix.vector_bits }}=on ./test/test_xsimd
      working-directory: ${{ github.workspace }}/_build
