name: macOS build
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os:
          - 14
          - 15
          - 15-intel
    runs-on: macos-${{ matrix.os }}
    name: 'macos-${{ matrix.os }}'
    steps:
    - uses: actions/checkout@v6
    - name: Setup
      run: cmake -B _build -DBUILD_TESTS=ON -DDOWNLOAD_DOCTEST=ON -DBUILD_BENCHMARK=ON -DBUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
    - name: Build
      run: cmake --build _build --verbose
    - name: Testing sequential
      run: cmake --build _build --target xbenchmark --verbose
    - name: Set CPU feature test expectations
      run: |
        if echo '${{ matrix.os }}' | grep -q intel; then
          echo "XSIMD_TEST_CPU_ASSUME_NEON64=0" >> "$GITHUB_ENV"
          echo "XSIMD_TEST_CPU_ASSUME_SSE4_2=1" >> "$GITHUB_ENV"
          echo "XSIMD_TEST_CPU_ASSUME_MANUFACTURER=intel" >> "$GITHUB_ENV"
        else
          echo "XSIMD_TEST_CPU_ASSUME_NEON64=1" >> "$GITHUB_ENV"
          echo "XSIMD_TEST_CPU_ASSUME_SSE4_2=0" >> "$GITHUB_ENV"
          echo "XSIMD_TEST_CPU_ASSUME_MANUFACTURER=unknown" >> "$GITHUB_ENV"
        fi
    - name: Testing xsimd
      run: ${{github.workspace}}/_build/test/test_xsimd
