name: macOS build
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        sys:
          - { os: '14',       arch: 'native' }
          - { os: '15',       arch: 'neon64' }
          - { os: '15-intel', arch: 'sse4.2' }
    runs-on: macos-${{ matrix.sys.os }}
    name: 'macos-${{ matrix.sys.os }} - ${{ matrix.sys.arch }}'
    steps:
    - uses: actions/checkout@v6
    - name: Setup
      run: |
        cmake -B _build \
          -D CMAKE_BUILD_TYPE=Release \
          -D BUILD_TESTS=ON \
          -D DOWNLOAD_DOCTEST=ON \
          -D BUILD_BENCHMARK=ON \
          -D BUILD_EXAMPLES=ON \
          -D TARGET_ARCH="${{ matrix.sys.arch }}"
    - name: Build
      run: cmake --build _build --verbose
    - name: Testing sequential
      run: cmake --build _build --target xbenchmark --verbose
    - name: Set CPU feature test expectations
      run: |
        echo "XSIMD_TEST_CPU_ASSUME_RVV=0" >> "$GITHUB_ENV"
        if echo '${{ matrix.sys.os }}' | grep -q intel; then
          echo "XSIMD_TEST_CPU_ASSUME_NEON64=0" >> "$GITHUB_ENV"
          echo "XSIMD_TEST_CPU_ASSUME_SSE4_2=1" >> "$GITHUB_ENV"
          echo "XSIMD_TEST_CPU_ASSUME_MANUFACTURER=intel" >> "$GITHUB_ENV"
        else
          echo "XSIMD_TEST_CPU_ASSUME_NEON64=1" >> "$GITHUB_ENV"
          echo "XSIMD_TEST_CPU_ASSUME_SSE4_2=0" >> "$GITHUB_ENV"
          echo "XSIMD_TEST_CPU_ASSUME_MANUFACTURER=unknown" >> "$GITHUB_ENV"
        fi
    - name: Testing xsimd
      run: ${{github.workspace}}/_build/test/test_xsimd
