name: Windows build
on: [push, pull_request]

jobs:
  build-windows-arm64:
    name: 'MSVC arm64'
    defaults:
      run:
        shell: bash {0}
    runs-on: windows-11-arm
    steps:
    - name: Setup compiler
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: arm64
    - name: Setup Ninja
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install ninja
    - name: Checkout xsimd
      uses: actions/checkout@v6
    - name: Setup
      run: cmake -B _build -DBUILD_TESTS=ON -DDOWNLOAD_DOCTEST=ON -DBUILD_BENCHMARK=ON -DBUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Release -G Ninja
    - name: Build
      run: cmake --build _build
    - name: Testing xsimd
      run: ./_build/test/test_xsimd
